#!/bin/bash

source $(dirname $0)/prompt.sh

prompt "Replica" "" "REPLICA"
prompt "Servers" "" "SERVERS"
prompt "User" "" "USER"
prompt "Password" "" "PASSWORD"
prompt "Database" "" "DATABASE"

docker run -it --rm \
  -v "$PWD:/src" \
  mongo:latest \
  sh -c "mongodump -h $REPLICA/$SERVERS -u $USER -p $PASSWORD -d $DATABASE --ssl --authenticationDatabase admin -o /src"

